title: Zach's Pages
description: Personal blog and project docs
theme: minima

# Blog settings
permalink: /blog/:year/:month/:day/:title/

# Minima theme settings
minima:
  date_format: "%Y-%m-%d"
  social_links:
    github: ZachVec

# Build settings
markdown: kramdown
exclude:
  - _docsrc
  - vendor
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .gitmodules
plugins:
  - jekyll-feed
  - jekyll-seo-tag
